[package]
name = "term-wm"
description = "A cross-platform window manager for terminal shells."
authors = ["Jeremy Harris <jeremy.harris@zenosmosis.com>"]
version = "0.4.1-alpha"
edition = "2024"
repository = "https://github.com/jzombie/term-wm"
license = "MIT OR Apache-2.0"
publish = true

default-run = "term-wm"

[package.metadata.cargo-udeps.ignore]
normal = ["windows-sys"]

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
crossterm = "0.29.0"
hostname = "0.4.2"
indoc = "2.0.7"
libc = "0.2.176"
line-ending = "1.5.1"
linkify = "0.10.0"
portable-pty = "0.9.0"
pulldown-cmark = "0.13.0"
ratatui = "0.30.0"
resvg = "0.45.1"
shell-words = "1.1.1"
thiserror = "2.0.17"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
vt100 = "0.16.2"
webbrowser = "1.0.6"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_IO"] }

[build-dependencies]
indoc = "2.0.7"
